SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68DD200300AD975D}" {
     m_sEntityPrefab "{C3331802F687D1BC}Prefabs/IED/BH_Wirecutter.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68DD20031C8E92AF}" {
       m_eItemType EQUIPMENT
      }
     }
    }
   }
  }
 }
}