SCR_NameTagConfig {
 m_sNametagLayout "{A641874FD415B0D2}UI/layouts/HUD/NameTag/BH_NameTag.layout"
 m_aSourceEntities SCR_NameTagCollectorBase "{617F66F670C7B41D}" {
 }
 m_aVisibilityRuleset SCR_NameTagRulesetFriendlies "{617F66F670C7B407}" {
 }
 m_aZones {
  SCR_NameTagZone "{617F66F670C7B403}" {
   m_sZoneName "Near"
   m_iZoneEnd 5
   m_aElements {
    SCR_NTName "{5D9887870EE2CBFF}" : "{29BC0B4F35D6125E}Configs/NameTags/NameTagPlayerNameElement.conf" {
     m_aEntityStates {
      SCR_NTStateText "{5878A68DE0CE9E48}" {
       m_vColor 1 0.842 0 1
      }
     }
    }
    SCR_NTIconBase "{5D988780FD72C0CE}" : "{142E72BE45CD9E35}Configs/NameTags/NameTagIconElement.conf" {
     m_aEntityStates {
      SCR_NTStateIcon "{5D988792C90BE88E}" {
       m_vColor 1 0 0 1
      }
     }
    }
    SCR_NTIconBase "{5D9CD06C8E74938D}" : "{C54403D9C13E5642}Configs/NameTags/NameTagIconShadowElement.conf" {
    }
   }
  }
 }
}