SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD5F7414CA4A}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68DD2946182F212B}" {
     m_sEntityPrefab "{C3331802F687D1BC}Prefabs/IED/BH_Wirecutter.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68DD294617857C20}" {
       m_eItemType EQUIPMENT
      }
     }
    }
   }
  }
 }
}