SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453BCB39DC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{684F22C720BDDF65}" {
     m_sEntityPrefab "{73950FBA2D7DB5C5}Prefabs/Items/Equipment/Radios/Radio_ANPRC68.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{684F22C743D10D0A}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68DD2002A20FE2C9}" {
     m_sEntityPrefab "{C3331802F687D1BC}Prefabs/IED/BH_Wirecutter.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68DD2002BF660C31}" {
       m_eItemType EQUIPMENT
      }
     }
    }
   }
  }
 }
}