ActionManager {
 Actions {
  Action BH_HoldBreath {
   InputSource InputSourceSum "{68F51B9DA1E3E473}" {
    Sources {
     InputSourceValue "{68F51B9DA5A94247}" {
      FilterPreset "BH_Key_HoldBreath"
      Input "keyboard:KC_F4"
      Filter InputFilterHold "{68F71A9B06B65031}" {
      }
     }
    }
   }
  }
  Action BH_FireSupportMenu {
   InputSource InputSourceSum "{690F18B80820F6F9}" {
    Sources {
     InputSourceValue "{690F18B801C46FFA}" {
      FilterPreset "BH_Key_FireSupport"
      Input "keyboard:KC_F5"
      Filter InputFilterClick "{690F18B8154195C9}" {
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext CharacterWeaponContext {
   ActionRefs +{
    "BH_HoldBreath"
    "BH_FireSupportMenu"
   }
  }
  ActionContext BH_FireSupportMenuContext {
   ActionRefs +{
	"BH_FireSupportMenu"
   }
  }
 }
}