SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{68F52AE5E6E94D87}" {
   m_sName "BhelmaCore"
   m_sDisplayName "BHELMA CORE"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{68F52AE20D9A683C}" {
     m_sActionName "BH_HoldBreath"
     m_sDisplayName "Mantener Respiracion - Hold Breath"
     m_sPreset "BH_Key_HoldBreath"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{690F18B84247C6C5}" {
     m_sActionName "BH_FireSupportMenu"
     m_sDisplayName "Menu Solicitar Soporte - Support Menu"
     m_sPreset "BH_Key_FireSupport"
     m_ePrefixType CONTINUOUS
    }
   }
  }
 }
}