SCR_MissionHeaderCombatOps {
 World "{27E6523408AD86A6}Worlds/BH_Core_Mision.ent"
 SystemsConfig "{86E953538A28A98E}Configs/Systems/ChimeraSystemsConfig.conf"
 m_sName "BH Core Mision"
 m_sAuthor "Bhelma"
 m_sPath "Missions/BH_Core_Mision.conf"
 m_sDescription "Sus cosas"
 m_sDetails "Sus cosas"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 6
 m_bOverrideScenarioTimeAndWeather 1
 m_bRandomStartingDaytime 1
 m_aTaskTypesAvailable {
  SCR_ScenarioFrameworkTaskType "{5E38A8A41B55DA84}" {
   m_eTypeOfTask DELIVER
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A41B2725C3}" {
   m_eTypeOfTask DESTROY
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A41BE3799A}" {
   m_eTypeOfTask CLEAR_AREA
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A41B944989}" {
   m_eTypeOfTask KILL
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A40B5073D5}" {
   m_eTypeOfTask DEFEND
  }
 }
}